#!/usr/bin/env bash

PYTHON=python3

if [ -n "$1" ]; then
  PYTHON=$1
fi

pushd $(dirname $0)
  if [ ! -d env ]; then
    virtualenv -p $PYTHON env
  fi

  . env/bin/activate
  pip install -r requirements.txt

  python -m debugpy --wait-for-client --listen 0.0.0.0:5678 main.py
popd

